#Cabeceras csv

FECHA_DESDE = '[Fecha Desde Hecho].[Dia Desde Hecho]'

LUGAR_HECHO_TIPO_VIA = '[Lugar Hecho Via].[Lugar Hecho Tipo Via]'
LUGAR_HECHO_VIA = '[Lugar Hecho Via].[Lugar Hechos Via]'
LUGAR_HECHO_MUNICIPIO = '[Lugar Hecho].[Municipio Hecho]'
LUGAR_HECHO_PROVINCIA = '[Lugar Hecho].[Provincia Hecho]'
LUGAR_HECHO_CONTINENTE = '[Lugar Hecho Pais].[Continente Hecho]'
LUGAR_HECHO_PAIS = '[Lugar Hecho Pais].[Pais Hecho]'
LUGAR_HECHO_JEFATURA = '[Lugar Hecho].[Jefatura Hecho]'
LUGAR_HECHO_DISTRITO = '[Lugar Hecho Distrito].[Lugar Hecho Distrito]'

RESPONSABLE_DNI = '[Identificacion Responsable].[Numero Documento Responsable]'
RESPONSABLE_EDAD = '[Edad Responsable].[Edades Responsable]'
RESPONSABLE_SEXO = '[Sexo Responsale].[Sexo Responsable]'
RESPONSABLE_NACIONALIDAD = '[Nacionalidad Actual Responsable].[Nacionalidad Actual Responsable]'
RESPONSABLE_MUNICIPIO = '[Lugar Residencia Responsable].[Municipio Residencia Responsable]'
RESPONSABLE_PAIS = '[Pais Residencia Responsable].[Paises Residencia Responsable]'
RESPONSABLE_EXTRANJERIA = '[Situacion Extranjero EspaÃ±a Responsable].[Situacion Extranjero EspaÃ±a Responsable]'
RESPONSABLE_ENTRADA_EXTRANJERO = '[Medio Utilizado Entrada Ilegal Responsable].[Medio Utilizado Entrada Ilegal Responsable]'
RESPONSABLE_DETENCIONES = '[Numero Detenciones Responsable].[Numero Detenciones Responsable]'

PLANTILLA_ACTUACION_UNIDAD_COD ='[Plantilla Actuacion].[Unidad Cod]'
PLANTILLA_ACTUACION_PLANTILLA_COD = '[Plantilla Actuacion].[Plantilla Cod]'
PLANTILLA_ACTUACION_ACTUACION = '[Plantilla Actuacion].[Unidad Actuacion]'
PLANTILLA_ACTUACION_JEFATURA = '[Plantilla Actuacion Lugar].[Plantilla Actuacion Jefatura]'
PLANTILLA_ACTUACION_PROVINCIA = '[Plantilla Actuacion Lugar].[Plantilla Actuacion Provincia]'
PLANTILLA_ACTUACION_MUNICIPIO = '[Plantilla Actuacion Lugar].[Plantilla Actuacion Municipio]'

ACTUACION_DIA = '[Fecha Actuacion].[Dia Actuacion]'
ACTUACION_PLANTILLAS = '[Plantilla Actuacion].[Plantillas Actuacion]'
ACTUACION_ORIGEN = '[Origen Actuacion].[Origen Actuacion]'
ACTUACION_NUMERO = '[NumActuacion].[Numactuacion]'

HECHO_GRUPOS_TIPO = '[Tipo Hecho].[Grupo Tipos Hecho]'
HECHO_TIPOS = '[Tipo Hecho].[Tipos Hecho]'
HECHO_CALIFICACION = '[Calificacion Hecho].[Calificacion Hecho]'
HECHO_GRADO_EJECUCION = '[Grado Ejecucion Hecho].[Grado Ejecucion Hecho]'
HECHO_MODUS_OPERANDI = '[Modus Operandi Hecho].[Modus Operandi Hecho]'
HECHO_RELACIONADO_TIPOS = '[Tipo Hecho Relacionado].[Tipos Hecho]'
HECHO_HORAS = '[Hora Desde Hecho].[Horas Desde Hecho]'
HECHO_LUGAR_GENERAL = '[Lugar General Hecho].[Lugar General]'
HECHO_GRUPO_LUGAR_ESPECIFICO = '[Lugar Especifico Hecho].[Grupo Lugar Especifico]'
HECHO_LUGARES_ESPECIFICOS = '[Lugar Especifico Hecho].[Lugares Especificos]'
